### PR TITLE
LDAPS support for 1.4.x

### LINKED ISSUE #1257: LDAP authentication fails with ldaps server
I want to use my university's LDAP server (anonymized below as authorise.uni.ac.uk) for OpenCGA authentication. The LDAP server is accessed via ldaps protocol on port 636. It appears that the URL is not being correctly parsed - it comes out as '/authorise.uni.ac.uk' instead of 'authorise.uni.ac.uk' in the error messages. When I use ldap:// instead of ldaps:// the host name is correctly identified, but won't connect as it's the wrong port/protocol combination.

configuration.yml:
```
authentication:
  # Session expiration time in seconds
  expiration: 3600
# LDAP configuration example
  authenticationOrigins:
  - id: UNI_LDAP            # Any id
    type: LDAP
    host: ldaps://authorise.uni.ac.uk:636
    options:
      usersSearch: dc=authorise,dc=uni,dc=ac,dc=uk # Base search to look for the users
      groupsSearch: ou=people,ou=central,dc=authorise,dc=uni,dc=ac,dc=uk # Base search to look for the groups
```
Error:
```
[opencga@server conf]$ opencga-admin.sh users import --auth-origin UNI_LDAP -u ameyner2
Admin password: 
2019-04-15 20:31:01 [main] ERROR LDAPAuthenticationManager:93 - Invalid name: /authorise.uni.ac.uk:636
javax.naming.InvalidNameException: Invalid name: /authorise.uni.ac.uk:636
	at javax.naming.ldap.Rfc2253Parser.parseAttrType(Rfc2253Parser.java:155)
	at javax.naming.ldap.Rfc2253Parser.doParse(Rfc2253Parser.java:108)
	at javax.naming.ldap.Rfc2253Parser.parseDn(Rfc2253Parser.java:70)
	at javax.naming.ldap.LdapName.parse(LdapName.java:785)
	at javax.naming.ldap.LdapName.<init>(LdapName.java:123)
	at com.sun.jndi.ldap.LdapNameParser.parse(LdapNameParser.java:39)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:302)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getDirContext(LDAPUtils.java:48)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getUserInfoFromLDAP(LDAPUtils.java:144)
	at org.opencb.opencga.catalog.auth.authentication.LDAPAuthenticationManager.authenticate(LDAPAuthenticationManager.java:74)
	at org.opencb.opencga.catalog.managers.UserManager.login(UserManager.java:506)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.importUsersAndGroups(UsersCommandExecutor.java:133)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.execute(UsersCommandExecutor.java:61)
	at org.opencb.opencga.app.cli.admin.AdminMain.main(AdminMain.java:129)
2019-04-15 20:31:01 [main] INFO  UserManager:331 - Fetching user information from authentication origin 'UNI_LDAP'
2019-04-15 20:31:04 [main] ERROR LDAPAuthenticationManager:121 - Could not retrieve user information Invalid name: /authorise.uni.ac.uk:636
{}
javax.naming.InvalidNameException: Invalid name: /authorise.uni.ac.uk:636
	at javax.naming.ldap.Rfc2253Parser.parseAttrType(Rfc2253Parser.java:155)
	at javax.naming.ldap.Rfc2253Parser.doParse(Rfc2253Parser.java:108)
	at javax.naming.ldap.Rfc2253Parser.parseDn(Rfc2253Parser.java:70)
	at javax.naming.ldap.LdapName.parse(LdapName.java:785)
	at javax.naming.ldap.LdapName.<init>(LdapName.java:123)
	at com.sun.jndi.ldap.LdapNameParser.parse(LdapNameParser.java:39)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:302)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getDirContext(LDAPUtils.java:48)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getUserInfoFromLDAP(LDAPUtils.java:144)
	at org.opencb.opencga.catalog.auth.authentication.LDAPAuthenticationManager.getRemoteUserInformation(LDAPAuthenticationManager.java:119)
	at org.opencb.opencga.catalog.managers.UserManager.importRemoteUsers(UserManager.java:333)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.importUsersAndGroups(UsersCommandExecutor.java:136)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.execute(UsersCommandExecutor.java:61)
	at org.opencb.opencga.app.cli.admin.AdminMain.main(AdminMain.java:129)
org.opencb.opencga.catalog.exceptions.CatalogException: Could not retrieve user information
Invalid name: /authorise.uni.ac.uk:636
	at org.opencb.opencga.catalog.auth.authentication.LDAPAuthenticationManager.getRemoteUserInformation(LDAPAuthenticationManager.java:122)
	at org.opencb.opencga.catalog.managers.UserManager.importRemoteUsers(UserManager.java:333)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.importUsersAndGroups(UsersCommandExecutor.java:136)
	at org.opencb.opencga.app.cli.admin.executors.UsersCommandExecutor.execute(UsersCommandExecutor.java:61)
	at org.opencb.opencga.app.cli.admin.AdminMain.main(AdminMain.java:129)
Caused by: javax.naming.InvalidNameException: Invalid name: /authorise.uni.ac.uk:636
	at javax.naming.ldap.Rfc2253Parser.parseAttrType(Rfc2253Parser.java:155)
	at javax.naming.ldap.Rfc2253Parser.doParse(Rfc2253Parser.java:108)
	at javax.naming.ldap.Rfc2253Parser.parseDn(Rfc2253Parser.java:70)
	at javax.naming.ldap.LdapName.parse(LdapName.java:785)
	at javax.naming.ldap.LdapName.<init>(LdapName.java:123)
	at com.sun.jndi.ldap.LdapNameParser.parse(LdapNameParser.java:39)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:302)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getDirContext(LDAPUtils.java:48)
	at org.opencb.opencga.catalog.auth.authentication.LDAPUtils.getUserInfoFromLDAP(LDAPUtils.java:144)
	at org.opencb.opencga.catalog.auth.authentication.LDAPAuthenticationManager.getRemoteUserInformation(LDAPAuthenticationManager.java:119)
	... 4 more
```

### PR DESCRIPTION
**Pull request by mwhamgenomics**
Adds support for ldaps:// connections to LDAPConfigurationManager. Closes #1257 . Also adds some config options to accommodate variations in the structures of different LDAP installations.

### CODE REVIEW

File: opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPAuthenticationManager.java [hunk 1]
```diff
@@ -84,9 +97,17 @@ public String authenticate(String username, String password) throws CatalogAuthe
...
 
             env.put(Context.SECURITY_AUTHENTICATION, "simple");
-            env.put(Context.SECURITY_PRINCIPAL, rdn);
             env.put(Context.SECURITY_CREDENTIALS, password);
 
+            if (ldaps) {
+                String uid = userInfoFromLDAP.get(0).get(dnKey).get(0).toString();
+                String dn = String.format(dnFormat, uid);
+                env.put(Context.SECURITY_PRINCIPAL, dn);
+                env.put(Context.SECURITY_PROTOCOL, "ssl");
```
Comment (mwhamgenomics) [inline opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPAuthenticationManager.java:106]: Authentication still works without setting "ssl" here

File: opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPAuthenticationManager.java [hunk 2]
```diff
@@ -84,9 +97,17 @@ public String authenticate(String username, String password) throws CatalogAuthe
...
+            } else {
+                env.put(Context.SECURITY_PRINCIPAL, rdn);
```
Comment (mwhamgenomics) [inline opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPAuthenticationManager.java:108]: The original/default behaviour here was to pass the contents of `gecos` to the auth request rather than a distinguished name like `uid=a_user,ou=people...`. Does this work?

File: opencga-core/src/main/java/org/opencb/opencga/core/config/AuthenticationOrigin.java [hunk 3]
```diff
@@ -38,6 +38,9 @@
     // Possible keys of the options map
     public static final String USERS_SEARCH = "usersSearch";
     public static final String GROUPS_SEARCH = "groupsSearch";
+    public static final String FULLNAME_KEY = "fullNameKey";
+    public static final String DN_KEY = "dnKey";
+    public static final String DN_FORMAT = "dnFormat";
```
Comment (mwhamgenomics) [inline opencga-core/src/main/java/org/opencb/opencga/core/config/AuthenticationOrigin.java:43]: I wasn't sure what to call these options. Any better ideas?

File: opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPAuthenticationManager.java (hunk 2 above)
Comment (mwhamgenomics) [reply opencga-catalog/src/main/java/org/opencb/opencga/catalog/auth/authentication/LDAPAuthenticationManager.java:108]: Looks like in other cases, the gecos is formatted correctly. In other LDAP systems though, the distinguished name may be stored in a different attribute, or just as the ID of the user object from the search:

```python
>>> import ldap
>>> l = ldap.initialize(ldap_url)
>>> l.search_s(base_dn, ldap.SCOPE_SUBTREE, '(uid=me)')
[
    (
        "uid=me,ou=people,dc=ge,dc=co,dc=uk",  # DN could be here...
        {
            "uid": "me",
            "gecos": "uid=me,ou=people,dc=ge,dc=co,dc=uk",  # ... or here (default OpenCGA behaviour)...
            "some_other_field": "uid=me,ou=people,dc=ge,dc=co,dc=uk"  # ... or here
        }
    )
]
```

So we still need some way of telling OpenCGA where to find the DN, but it may be possible to remove some of the added config options
